DROP database IF EXISTS freespirits_db;

CREATE database freespirits_db;
USE freespirits_db;

CREATE TABLE trips(
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  creator_id INTEGER(11),
  title VARCHAR(100),
  destination VARCHAR(100),
  starting_date DATE,
  end_date DATE,
  duration INTEGER(3),
  travel_philosophy VARCHAR(100),
  description VARCHAR(500),
  budget_day INTEGER(4),
  currency VARCHAR(30),
  users VARCHAR(255),
  status VARCHAR(30) DEFAULT "Open",
  group_size INTEGER(2),
  primary_language VARCHAR(30),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE profiles(
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  fname VARCHAR(50),
  lname VARCHAR(50),
  gender VARCHAR(30),
  picture VARCHAR(500),
  travel_philosophy VARCHAR(100),
  description VARCHAR(500),
  email VARCHAR(100),
  primary_language VARCHAR(30),
  status VARCHAR(30) DEFAULT "Active",
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO profiles(fname, lname, travel_philosophy, description, email, primary_language, gender)
VALUES ("Janet", "Kim", "Wild", "I like to have fun and go to a lot of different places!", "test@gmail.com", "English", "female"),
("Florida", "Morrow", "Relaxed", "I like to eat food and not take a lot of photos", "florida@gmail.com", "English", "female"),
("Octoman", "Bruno", "Wild", "I want to travel the world, okay?!", "VRAII@gmail.com", "English", "male");

INSERT INTO profiles (fname,lname,travel_philosophy,description,email,primary_language,gender) VALUES ("Jordan","Gay","Anything Goes","Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris.","sed.libero.Proin@blandit.co.uk","English","female"),
("Azalia","Chang","Frugal","diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra","Pellentesque.ultricies@nascetur.co.uk","Spanish","male"),
("Heidi","Hawkins","Anything Goes","commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus","est.mollis.non@congue.edu","English","male"),
("Gil","Rivers","Frugal","elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris","nec@adipiscingelitEtiam.org","Spanish","female"),
("Stone","Cameron","Relaxed","pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam","diam@risusDonec.org","English","nonbinary"),
("Summer","Gates","Frugal","eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae,","felis@libero.com","French","male"),
("Steel","Ward","Frugal","nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus.","fringilla@dapibusquamquis.edu","English","female"),
("Adara","Raymond","Frugal","sit amet ornare lectus justo eu arcu. Morbi sit amet","Praesent@variusorci.ca","French","male"),
("Azalia","Burke","Anything Goes","nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam","aliquam@convallisestvitae.edu","English","female"),
("Selma","Cameron","Wild","et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque.","orci.Ut@Nullam.net","English","female"),
("Rafael","Sandoval","Anything Goes","vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse","non.bibendum@fermentum.co.uk","French","male"),
("Ferdinand","Kane","Relaxed","accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat,","scelerisque.lorem@felisullamcorper.net","English","nonbinary"),
("David","Goodman","Wild","a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet,","Duis@pharetra.edu","English","female"),
("TaShya","Ward","Picture-tastic","ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh.","gravida.sit@odio.net","Spanish","female"),
("Levi","Rowe","Picture-tastic","egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla","ante@metus.net","French","male"),
("Iliana","Duke","Wild","nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue","turpis.vitae@arcuAliquam.com","English","female"),
("Francis","Wilson","Anything Goes","non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras","Fusce.aliquet@quisdiam.net","English","nonbinary"),
("Marcia","Ramsey","Relaxed","varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur","ut.molestie.in@elitfermentum.org","Spanish","female"),
("Melodie","Joyce","Frugal","cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt","sodales.at.velit@vitaeorci.com","Spanish","female"),
("Damian","Nielsen","Wild","feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor,","risus.Nulla.eget@Maecenasliberoest.org","French","female");

INSERT INTO profiles (fname,lname,travel_philosophy,description,email,primary_language,gender) VALUES ("Cameron","Joyner","Relaxed","nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate,","egestas.Aliquam@pharetra.edu","English","female"),
("Dai","Pate","Anything Goes","facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna","nisl.Quisque.fringilla@idblanditat.org","Spanish","female"),
("Kim","Valenzuela","Picture-tastic","dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus","sed.dui@leoelementumsem.net","French","nonbinary"),
("Jakeem","Martin","Relaxed","Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum","sed.est.Nunc@arcuSed.com","English","nonbinary"),
("Silas","Dunlap","Wild","eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,","sed@semegestasblandit.net","Spanish","female"),
("Chaney","Sargent","Frugal","mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et,","lorem.sit.amet@egetlaoreetposuere.co.uk","English","male"),
("Briar","Puckett","Frugal","mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor","ipsum.non@molestie.com","English","nonbinary"),
("Inga","Hensley","Anything Goes","malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus,","metus@musProin.com","French","male"),
("Xenos","Hudson","Picture-tastic","in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum","amet.ornare@vitae.com","English","male"),
("Dorothy","King","Picture-tastic","molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu","cursus@quis.net","Spanish","male"),
("Kimberley","Rojas","Anything Goes","vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet","lobortis@tristiqueaceleifend.net","Spanish","female"),
("Indigo","Landry","Relaxed","Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim","ac.mattis.ornare@Crasdictumultricies.org","Spanish","nonbinary"),
("Breanna","Parrish","Picture-tastic","eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis,","consectetuer.ipsum.nunc@dignissimmagna.com","English","male"),
("Kim","Woodard","Anything Goes","non massa non ante bibendum ullamcorper. Duis cursus, diam at","sem.consequat@luctusipsum.com","English","nonbinary"),
("Gwendolyn","Swanson","Frugal","lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis","Mauris.molestie@dignissimlacusAliquam.edu","English","male"),
("Jillian","Stafford","Anything Goes","Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus","Morbi.sit@egetvariusultrices.edu","English","male"),
("Nero","Pratt","Wild","Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas","vel.turpis.Aliquam@mollisvitae.org","English","male"),
("Anthony","Rosa","Relaxed","morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce","Donec.sollicitudin.adipiscing@sagittisfelisDonec.co.uk","Spanish","male"),
("Tanner","Best","Picture-tastic","orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec","a.scelerisque@litoratorquentper.org","Spanish","female"),
("Quail","Clements","Picture-tastic","ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien,","non@purusac.edu","English","male");

INSERT INTO profiles (fname,lname,travel_philosophy,description,email,primary_language,gender) VALUES ("Xanthus","Davidson","Frugal","a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu.","lacus@scelerisquesed.org","French","female"),
("Cheryl","Hatfield","Relaxed","consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate","Nullam@neceuismodin.edu","English","male"),
("Clarke","Patrick","Anything Goes","non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna","Vestibulum.accumsan.neque@Nam.edu","English","male"),
("Christen","Gilbert","Frugal","Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede","sociis.natoque.penatibus@duinecurna.org","Spanish","female"),
("Vernon","Nixon","Relaxed","auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo","a.scelerisque.sed@blanditcongue.ca","Spanish","male"),
("Veda","Lloyd","Frugal","eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla","Donec@habitant.co.uk","Spanish","male"),
("Channing","Monroe","Anything Goes","Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor","elit@diam.org","English","male"),
("Dexter","Travis","Picture-tastic","elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu","eu.elit@Morbi.ca","French","female"),
("Carly","Charles","Frugal","eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam.","nunc@sodalesMauris.net","English","male"),
("Lester","Rowe","Frugal","mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh","scelerisque.neque@variusNam.com","English","female"),
("Uriah","Sears","Wild","amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum","ac@quis.org","English","male"),
("Perry","Mason","Anything Goes","quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem","torquent.per.conubia@egetlaoreet.ca","French","male"),
("Calista","Parker","Frugal","fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem","sit@id.edu","French","female"),
("Drew","Stark","Anything Goes","orci. Ut semper pretium neque. Morbi quis urna. Nunc quis","et@neccursus.com","English","female"),
("Kylynn","Blankenship","Anything Goes","amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id","posuere.cubilia.Curae@inconsectetuer.edu","English","male"),
("Ursula","Carney","Wild","nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum","dolor.sit@velnislQuisque.net","English","male"),
("Prescott","Dale","Anything Goes","non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,","cursus@arcu.edu","French","male"),
("Tanya","Johnston","Wild","lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis","mollis@enim.edu","French","nonbinary"),
("Lani","Collins","Picture-tastic","Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula","interdum.feugiat.Sed@lectuspede.com","Spanish","male"),
("Priscilla","Valdez","Relaxed","turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam","Suspendisse.tristique.neque@parturientmontes.edu","English","male");

INSERT INTO profiles (fname,lname,travel_philosophy,description,email,primary_language,gender) VALUES ("Reed","Morrison","Frugal","fames ac turpis egestas. Fusce aliquet magna a neque. Nullam","Nullam@odio.co.uk","English","female"),
("Clinton","Morales","Anything Goes","odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit","nec@metusurnaconvallis.net","English","female"),
("Jeremy","Stein","Frugal","nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et,","Phasellus.nulla@magnaPraesentinterdum.ca","English","female"),
("Aaron","Mcbride","Frugal","per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In","Aliquam.auctor@Nuncsollicitudin.com","Spanish","female"),
("Tarik","Ingram","Picture-tastic","sodales elit erat vitae risus. Duis a mi fringilla mi","at.sem.molestie@velvulputate.com","English","female"),
("Austin","Hunter","Wild","massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem","orci.Phasellus@euismod.edu","French","male"),
("Luke","Haley","Anything Goes","non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna","Etiam.laoreet.libero@sed.edu","English","male"),
("Dorian","Meadows","Frugal","lectus sit amet luctus vulputate, nisi sem semper erat, in","Curabitur.egestas@Pellentesqueut.ca","English","nonbinary"),
("Regina","Howe","Frugal","Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum","Cras.convallis@non.edu","English","nonbinary"),
("Rhona","Frazier","Picture-tastic","nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit.","urna.Nunc@metus.org","French","male"),
("Dominic","Campos","Picture-tastic","nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis.","a.purus.Duis@vulputatemauris.org","Spanish","female"),
("Oren","Leon","Relaxed","lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit","Cum.sociis.natoque@turpisegestas.net","English","female"),
("Janna","Vinson","Wild","nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum","Maecenas.ornare.egestas@leoin.co.uk","English","male"),
("Vladimir","Spencer","Anything Goes","quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur","neque.Morbi@lectusconvallisest.net","Spanish","male"),
("Kimberley","Spencer","Picture-tastic","mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh","tellus@necanteMaecenas.net","Spanish","female"),
("MacKensie","Hart","Frugal","velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate","nisl.sem.consequat@enim.edu","French","female"),
("Fletcher","Henson","Frugal","gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum","vestibulum.nec.euismod@elit.com","English","female"),
("Vanna","Griffin","Wild","nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus.","tincidunt.nibh.Phasellus@nonleoVivamus.co.uk","English","male"),
("Elaine","Noel","Anything Goes","Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla","Nulla@acmi.ca","English","nonbinary"),
("Clare","Hoffman","Relaxed","dui. Cum sociis natoque penatibus et magnis dis parturient montes,","adipiscing.lobortis@arcuSedet.com","Spanish","female");
INSERT INTO profiles (fname,lname,travel_philosophy,description,email,primary_language,gender) VALUES ("Alfreda","Maynard","Frugal","eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit,","Sed.nunc.est@sitametornare.net","English","male"),
("Zia","George","Anything Goes","gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi","tortor@quisurnaNunc.org","English","male"),
("Ciaran","Waters","Wild","a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum","Donec.est.Nunc@sem.com","French","female"),
("Michael","Carey","Relaxed","ante ipsum primis in faucibus orci luctus et ultrices posuere","Proin@risusDonecegestas.ca","English","female"),
("Clark","Booth","Anything Goes","tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus","sapien@turpis.ca","English","female"),
("Lila","Rocha","Picture-tastic","arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,","eget@feugiatmetus.co.uk","French","female"),
("Timon","Cole","Picture-tastic","pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis,","dolor.Fusce@auctor.ca","Spanish","female"),
("Karina","Bond","Wild","sed pede. Cum sociis natoque penatibus et magnis dis parturient montes,","malesuada@seddolorFusce.edu","Spanish","female"),
("Fallon","Hopper","Relaxed","cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo","Vestibulum@Curae.edu","English","female"),
("Cyrus","Long","Frugal","malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada","vitae.semper.egestas@malesuadafamesac.co.uk","Spanish","male"),
("Cally","Erickson","Anything Goes","vitae erat vel pede blandit congue. In scelerisque scelerisque dui.","tincidunt@ametultricies.org","French","female"),
("Kenneth","Hardy","Picture-tastic","felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu,","erat.Etiam.vestibulum@Ut.edu","French","male"),
("Brynn","Daugherty","Wild","eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus","Donec.egestas.Duis@dui.org","English","male"),
("Adrienne","Neal","Frugal","vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,","rutrum.eu@nequeet.edu","English","female"),
("Callie","Cochran","Anything Goes","eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu","Sed.auctor@hendreritconsectetuer.co.uk","Spanish","female"),
("Dale","Smith","Picture-tastic","montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque","Duis.mi.enim@inceptoshymenaeosMauris.net","English","male"),
("Demetria","Mcdowell","Relaxed","lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae,","risus.Donec.egestas@Vivamusmolestie.org","English","male"),
("Holly","Blevins","Anything Goes","Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum","sodales@egestasadui.co.uk","Spanish","male"),
("Jaden","Sweet","Relaxed","viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit","diam.Proin.dolor@nibhsitamet.org","French","female"),
("Giacomo","Mcfarland","Picture-tastic","adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper,","Nunc.commodo.auctor@egestas.net","English","nonbinary");

INSERT INTO trips(title, creator_id, destination, starting_date, end_date, duration, travel_philosophy, description, budget_day, currency, status, group_size, primary_language)
VALUES ("Trip to Mexico!", 1, "Mexico City", "2019-09-10", "2019-10-25", 10, "Wild", "Come have some fun in Mexico City!", 100, "USD", "Open", 6, "English"),
("Machu Picchu!!!!", 1, "Cusco", "2019-09-10", "2019-10-25", 4, "Wild", "Come have some fun taking a bus up to Machu Picchu!", 50, "USD", "Open", 3, "English"),
("Asia somewhere", 2, "Seoul", "2019-10-12", "2019-12-25", 19, "Foody", "I honestly just need to eat some good food and want company.", 400, "USD", "Open", 3, "English");

INSERT INTO trips (title,creator_id,destination,starting_date,end_date,duration,travel_philosophy,description,budget_day,currency,status,group_size,primary_language) VALUES ("Trip to Micronesia!",17,"Micronesia","2019-08-14 02:55:38","2020-03-17 20:08:45",17,"Frugal","tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus",379,"USD","Open",10,"English"),
("Trip to Saint Vincent and The Grenadines!",9,"Saint Vincent and The Grenadines","2019-11-13 23:08:26","2020-03-12 00:14:48",18,"Anything Goes","sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui,",259,"USD","Open",9,"English"),
("Trip to Ukraine!",30,"Ukraine","2019-07-21 08:51:41","2020-07-13 11:07:06",6,"Anything Goes","feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien.",316,"USD","Open",10,"Spanish"),
("Trip to Jordan!",2,"Jordan","2019-07-09 05:19:22","2020-10-01 07:04:53",17,"Wild","lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra.",71,"USD","Open",8,"English"),
("Trip to Dominica!",3,"Dominica","2019-09-10 10:41:38","2020-01-31 12:10:56",12,"Anything Goes","Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit",177,"USD","Cancelled",8,"English"),
("Trip to Saint Lucia!",27,"Saint Lucia","2019-09-24 05:06:54","2020-04-22 06:44:17",20,"Frugal","Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis",430,"USD","Open",4,"French"),
("Trip to Grenada!",22,"Grenada","2019-08-23 03:08:08","2020-07-23 05:14:06",9,"Anything Goes","Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a",253,"USD","Open",5,"Spanish"),
("Trip to Bouvet Island!",9,"Bouvet Island","2019-08-02 06:56:50","2020-10-04 16:13:03",12,"Anything Goes","venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum",104,"USD","Closed",8,"English"),
("Trip to Croatia!",7,"Croatia","2019-10-01 15:28:06","2020-01-30 18:07:10",17,"Picture-tastic","posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis",178,"USD","Open",4,"French"),
("Trip to Gabon!",6,"Gabon","2019-10-08 21:07:05","2020-04-02 08:15:57",18,"Frugal","Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec,",56,"USD","Open",6,"Spanish"),
("Trip to Pitcairn Islands!",21,"Pitcairn Islands","2019-09-30 05:31:13","2020-02-22 20:53:21",21,"Picture-tastic","tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis,",431,"USD","Open",10,"French"),
("Trip to Taiwan!",11,"Taiwan","2019-11-17 09:40:34","2020-07-23 10:40:19",8,"Anything Goes","euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at",66,"USD","Closed",6,"English"),
("Trip to Cape Verde!",12,"Cape Verde","2019-10-24 15:08:28","2020-04-19 00:45:21",5,"Anything Goes","lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet",370,"USD","Open",5,"English"),
("Trip to Guinea-Bissau!",29,"Guinea-Bissau","2019-11-12 07:14:31","2020-03-26 13:17:34",12,"Picture-tastic","ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla",281,"USD","Closed",6,"English"),
("Trip to Northern Mariana Islands!",29,"Northern Mariana Islands","2019-10-31 01:32:42","2020-05-30 08:45:24",12,"Frugal","tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu,",479,"USD","Open",9,"English"),
("Trip to Malta!",19,"Malta","2019-07-15 13:19:01","2020-01-31 14:28:27",5,"Wild","arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit.",202,"USD","Open",4,"English"),
("Trip to Iran!",25,"Iran","2019-12-09 09:07:05","2020-06-07 14:46:20",6,"Frugal","aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam",387,"USD","Cancelled",4,"English"),
("Trip to Liechtenstein!",1,"Liechtenstein","2019-10-13 13:54:55","2020-09-30 08:11:52",11,"Frugal","eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",245,"USD","Closed",9,"Spanish"),
("Trip to Belgium!",8,"Belgium","2019-09-25 12:45:06","2020-10-17 22:40:25",25,"Picture-tastic","Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui.",202,"USD","Open",9,"French"),
("Trip to Christmas Island!",26,"Christmas Island","2019-09-05 21:52:46","2020-07-21 16:15:13",5,"Wild","ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis",401,"USD","Open",6,"Spanish");

INSERT INTO trips (title,creator_id,destination,starting_date,end_date,duration,travel_philosophy,description,budget_day,currency,status,group_size,primary_language) VALUES ("Trip to Reunion!",25,"Reunion","2019-07-23 07:00:30","2020-01-16 06:17:33",5,"Wild","nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor",331,"USD","Closed",7,"English"),
("Trip to Eritrea!",17,"Eritrea","2019-08-30 15:17:13","2020-03-07 17:58:04",12,"Frugal","adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a",243,"USD","Cancelled",8,"English"),
("Trip to Suriname!",24,"Suriname","2019-12-28 20:36:09","2020-03-26 18:53:05",17,"Picture-tastic","luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id",150,"USD","Open",4,"English"),
("Trip to Denmark!",14,"Denmark","2019-12-22 14:07:20","2020-09-04 11:10:33",17,"Frugal","tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor",146,"USD","Open",7,"English"),
("Trip to Bouvet Island!",13,"Bouvet Island","2019-08-22 01:32:31","2020-06-11 00:05:55",18,"Wild","nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus",500,"USD","Open",9,"English"),
("Trip to Bermuda!",19,"Bermuda","2019-12-22 22:17:06","2020-02-02 01:00:42",10,"Frugal","tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,",489,"USD","Cancelled",7,"English"),
("Trip to Falkland Islands!",7,"Falkland Islands","2019-07-25 12:22:33","2020-05-20 11:46:42",17,"Picture-tastic","tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit",463,"USD","Open",6,"English"),
("Trip to Czech Republic!",3,"Czech Republic","2019-09-23 20:12:25","2020-03-08 19:32:09",12,"Picture-tastic","elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam.",471,"USD","Open",9,"Spanish"),
("Trip to Tuvalu!",16,"Tuvalu","2019-08-28 10:37:50","2020-05-29 23:09:57",22,"Frugal","magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum",208,"USD","Closed",6,"English"),
("Trip to Mexico!",10,"Mexico","2019-10-23 03:50:59","2020-04-19 05:36:03",17,"Frugal","mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc",264,"USD","Open",8,"English"),
("Trip to Germany!",9,"Germany","2019-10-07 05:43:57","2020-01-29 11:56:23",19,"Picture-tastic","imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt",126,"USD","Open",7,"Spanish"),
("Trip to Moldova!",30,"Moldova","2019-11-28 06:04:32","2020-02-06 21:13:07",11,"Wild","sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum.",245,"USD","Open",10,"English"),
("Trip to Mexico!",15,"Mexico","2019-12-08 23:49:11","2020-08-10 11:26:49",7,"Wild","imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus",412,"USD","Open",5,"English"),
("Trip to Korea, North!",7,"Korea, North","2019-10-21 15:08:54","2020-07-14 06:58:06",24,"Wild","vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio",498,"USD","Cancelled",6,"French"),
("Trip to Denmark!",19,"Denmark","2019-08-18 11:44:18","2020-05-16 06:23:24",25,"Wild","tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis",94,"USD","Closed",10,"English"),
("Trip to Dominican Republic!",19,"Dominican Republic","2019-12-22 04:24:29","2020-10-08 16:34:42",6,"Frugal","urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum",147,"USD","Open",7,"Spanish"),
("Trip to Finland!",11,"Finland","2019-12-20 22:23:15","2020-05-08 20:59:31",11,"Frugal","vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed",55,"USD","Open",4,"English"),
("Trip to Nepal!",20,"Nepal","2019-10-14 00:26:34","2020-08-25 03:49:39",5,"Picture-tastic","Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus.",299,"USD","Closed",9,"English"),
("Trip to Sint Maarten!",11,"Sint Maarten","2019-12-03 20:11:58","2020-03-16 15:20:22",20,"Picture-tastic","ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse",225,"USD","Cancelled",5,"French"),
("Trip to Virgin Islands, British!",13,"Virgin Islands, British","2019-09-29 06:05:57","2020-03-31 17:22:56",12,"Picture-tastic","ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris",303,"USD","Open",7,"English");

INSERT INTO trips (title,creator_id,destination,starting_date,end_date,duration,travel_philosophy,description,budget_day,currency,status,group_size,primary_language) VALUES ("Trip to Georgia!",3,"Georgia","2019-10-19 13:16:21","2020-05-18 07:10:18",8,"Frugal","Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo",84,"USD","Open",6,"English"),
("Trip to Saint Kitts and Nevis!",11,"Saint Kitts and Nevis","2019-07-13 05:54:38","2020-02-03 14:41:02",8,"Frugal","enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam",136,"USD","Closed",7,"French"),
("Trip to Equatorial Guinea!",6,"Equatorial Guinea","2019-12-18 16:54:43","2020-03-16 14:29:30",14,"Frugal","sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce",97,"USD","Open",10,"English"),
("Trip to Swaziland!",6,"Swaziland","2019-11-19 10:58:54","2020-07-30 14:10:21",19,"Picture-tastic","velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis",430,"USD","Open",10,"English"),
("Trip to Papua New Guinea!",3,"Papua New Guinea","2019-07-20 01:03:02","2020-10-05 10:19:56",18,"Picture-tastic","risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi.",154,"USD","Open",6,"English"),
("Trip to Senegal!",1,"Senegal","2019-10-30 21:09:58","2020-02-27 16:39:45",24,"Picture-tastic","a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam",109,"USD","Closed",8,"English"),
("Trip to Oman!",30,"Oman","2019-08-19 18:21:21","2020-02-02 19:29:07",24,"Picture-tastic","venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus.",332,"USD","Open",9,"English"),
("Trip to Kiribati!",12,"Kiribati","2019-12-17 11:17:15","2020-10-23 21:28:30",5,"Anything Goes","dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci",208,"USD","Open",5,"English"),
("Trip to Chad!",26,"Chad","2019-08-10 12:02:36","2020-05-06 22:51:02",11,"Picture-tastic","Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec",376,"USD","Open",4,"English"),
("Trip to Australia!",26,"Australia","2019-12-28 01:10:48","2020-10-02 01:31:04",8,"Frugal","luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan",179,"USD","Open",6,"French"),
("Trip to Chad!",22,"Chad","2019-08-21 14:10:52","2020-09-05 11:37:10",8,"Picture-tastic","In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat",234,"USD","Closed",4,"Spanish"),
("Trip to Cameroon!",25,"Cameroon","2019-10-02 21:55:37","2020-10-23 11:17:41",6,"Picture-tastic","id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem",478,"USD","Open",5,"Spanish"),
("Trip to Germany!",10,"Germany","2019-12-01 10:30:30","2019-12-22 10:03:32",17,"Wild","id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec",171,"USD","Cancelled",6,"English"),
("Trip to China!",27,"China","2019-10-25 15:36:21","2020-06-26 13:07:02",10,"Frugal","et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt",204,"USD","Open",4,"English"),
("Trip to Bolivia!",15,"Bolivia","2019-10-02 09:52:04","2020-03-15 11:48:49",16,"Picture-tastic","blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam",188,"USD","Open",4,"English"),
("Trip to Singapore!",7,"Singapore","2019-12-12 21:29:02","2020-01-02 06:42:50",14,"Picture-tastic","libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna.",409,"USD","Open",4,"English"),
("Trip to Fiji!",13,"Fiji","2019-12-23 00:13:40","2020-01-26 15:02:45",22,"Frugal","dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus.",328,"USD","Open",6,"English"),
("Trip to Barbados!",25,"Barbados","2019-09-13 21:58:06","2020-06-04 04:14:31",6,"Wild","luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum",250,"USD","Closed",9,"English"),
("Trip to Grenada!",22,"Grenada","2019-07-21 06:31:18","2020-08-04 23:28:02",7,"Frugal","dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices.",167,"USD","Open",8,"Spanish"),
("Trip to Gibraltar!",1,"Gibraltar","2019-09-16 15:08:37","2020-02-11 11:45:39",25,"Anything Goes","urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus",101,"USD","Open",10,"English");

INSERT INTO trips (title,creator_id,destination,starting_date,end_date,duration,travel_philosophy,description,budget_day,currency,status,group_size,primary_language) VALUES ("Trip to Suriname!",20,"Suriname","2019-11-13 14:09:14","2020-07-20 12:56:59",9,"Wild","nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor",206,"USD","Closed",6,"English"),
("Trip to Kuwait!",2,"Kuwait","2019-08-03 02:20:47","2020-08-28 07:22:34",10,"Picture-tastic","erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor",399,"USD","Open",6,"French"),
("Trip to Madagascar!",25,"Madagascar","2019-09-07 16:04:17","2020-02-14 01:53:53",24,"Frugal","Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus",99,"USD","Open",4,"Spanish"),
("Trip to Tajikistan!",8,"Tajikistan","2019-10-30 01:19:37","2020-01-08 18:37:06",18,"Wild","libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer",428,"USD","Cancelled",7,"Spanish"),
("Trip to Paraguay!",7,"Paraguay","2019-12-24 20:46:42","2020-02-21 00:22:04",6,"Frugal","convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales",271,"USD","Cancelled",4,"French"),
("Trip to Jersey!",7,"Jersey","2019-12-11 20:13:13","2020-04-17 21:17:31",8,"Frugal","vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla",341,"USD","Open",9,"English"),
("Trip to Namibia!",29,"Namibia","2019-12-21 14:27:21","2020-05-02 04:00:05",13,"Frugal","metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna.",456,"USD","Open",9,"English"),
("Trip to Mauritania!",1,"Mauritania","2019-07-23 04:53:03","2020-07-19 18:04:55",14,"Picture-tastic","tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies",468,"USD","Open",5,"English"),
("Trip to South Sudan!",18,"South Sudan","2019-10-18 08:35:50","2020-03-16 18:57:18",22,"Frugal","Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis",192,"USD","Open",5,"English"),
("Trip to Thailand!",18,"Thailand","2019-07-22 11:00:39","2020-02-26 10:44:58",6,"Wild","dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus",161,"USD","Open",7,"Spanish"),
("Trip to Monaco!",18,"Monaco","2019-12-18 21:33:55","2020-10-09 19:08:11",23,"Frugal","elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut",339,"USD","Open",8,"French"),
("Trip to Palau!",22,"Palau","2019-07-16 19:21:25","2020-02-14 05:37:42",17,"Picture-tastic","netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer",74,"USD","Open",7,"English"),
("Trip to Nepal!",11,"Nepal","2019-08-05 17:16:11","2020-05-01 20:08:02",25,"Anything Goes","lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras",174,"USD","Open",10,"English"),
("Trip to Morocco!",9,"Morocco","2019-09-09 14:29:05","2020-04-04 16:33:12",6,"Wild","velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper",114,"USD","Closed",8,"Spanish"),
("Trip to French Polynesia!",10,"French Polynesia","2019-07-09 12:55:16","2020-09-22 22:51:38",8,"Frugal","Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci",64,"USD","Open",6,"English"),
("Trip to Afghanistan!",23,"Afghanistan","2019-07-22 09:45:09","2020-01-21 16:23:23",19,"Wild","iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis.",481,"USD","Open",8,"English"),
("Trip to Sint Maarten!",29,"Sint Maarten","2019-12-07 00:24:32","2020-02-20 15:20:53",7,"Wild","Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices",172,"USD","Open",9,"Spanish"),
("Trip to Korea, South!",29,"Korea, South","2019-07-23 20:07:52","2020-06-19 14:49:40",18,"Picture-tastic","quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero.",400,"USD","Open",4,"Spanish"),
("Trip to Ethiopia!",7,"Ethiopia","2019-10-15 20:02:39","2020-04-23 04:10:31",12,"Frugal","massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget",84,"USD","Open",8,"Spanish"),
("Trip to Uzbekistan!",23,"Uzbekistan","2019-11-22 02:04:54","2020-08-05 18:52:28",13,"Anything Goes","amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor",226,"USD","Open",9,"English");

INSERT INTO trips (title,creator_id,destination,starting_date,end_date,duration,travel_philosophy,description,budget_day,currency,status,group_size,primary_language) VALUES ("Trip to Israel!",23,"Israel","2019-12-20 23:32:04","2020-08-12 13:58:54",5,"Frugal","suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices",160,"USD","Open",6,"English"),
("Trip to Brazil!",21,"Brazil","2019-07-29 13:00:47","2020-09-04 12:59:16",22,"Anything Goes","elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus",429,"USD","Cancelled",9,"English"),
("Trip to Czech Republic!",3,"Czech Republic","2019-08-14 13:43:09","2020-06-07 19:06:44",21,"Picture-tastic","consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus",406,"USD","Open",9,"English"),
("Trip to Philippines!",9,"Philippines","2019-11-08 19:13:48","2020-06-03 01:18:19",17,"Wild","arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt",263,"USD","Closed",6,"English"),
("Trip to Cocos (Keeling) Islands!",19,"Cocos (Keeling) Islands","2019-08-08 06:07:05","2020-05-21 02:09:25",9,"Picture-tastic","vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis",324,"USD","Closed",6,"English"),
("Trip to Lesotho!",5,"Lesotho","2019-11-15 08:33:01","2020-06-27 16:08:41",17,"Anything Goes","adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper.",120,"USD","Open",8,"English"),
("Trip to Finland!",6,"Finland","2019-09-16 12:43:57","2020-07-27 10:14:21",6,"Picture-tastic","elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque",160,"USD","Open",4,"English"),
("Trip to Sudan!",5,"Sudan","2019-08-30 04:26:06","2020-09-07 22:09:14",18,"Anything Goes","nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum",416,"USD","Closed",7,"Spanish"),
("Trip to Montenegro!",4,"Montenegro","2019-09-27 19:50:32","2020-08-04 04:40:43",16,"Wild","vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus",474,"USD","Open",9,"English"),
("Trip to Aruba!",15,"Aruba","2019-11-15 10:33:06","2020-06-12 22:23:55",21,"Anything Goes","ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam.",51,"USD","Open",5,"English"),
("Trip to Libya!",29,"Libya","2019-12-03 02:56:40","2020-08-23 04:27:54",9,"Frugal","lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam",102,"USD","Open",8,"English"),
("Trip to Belize!",4,"Belize","2019-10-29 00:08:26","2020-01-10 10:53:05",6,"Frugal","ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin",200,"USD","Open",9,"English"),
("Trip to Oman!",1,"Oman","2019-10-05 18:39:17","2020-08-19 01:48:22",6,"Anything Goes","nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue",54,"USD","Open",7,"English"),
("Trip to Guatemala!",12,"Guatemala","2019-08-17 07:28:17","2020-07-02 19:59:03",8,"Anything Goes","at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet",211,"USD","Closed",10,"English"),
("Trip to Jamaica!",15,"Jamaica","2019-10-24 03:48:33","2020-04-10 22:42:47",14,"Anything Goes","malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non,",346,"USD","Open",10,"English"),
("Trip to Ethiopia!",24,"Ethiopia","2019-10-21 20:46:17","2020-04-02 14:30:51",6,"Anything Goes","scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit",375,"USD","Cancelled",10,"English"),
("Trip to India!",18,"India","2019-11-08 20:44:46","2020-02-03 15:32:47",13,"Anything Goes","consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus",385,"USD","Open",7,"English"),
("Trip to Costa Rica!",14,"Costa Rica","2019-09-18 09:55:37","2020-05-21 02:05:36",19,"Frugal","odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer",128,"USD","Closed",7,"English"),
("Trip to Montserrat!",2,"Montserrat","2019-10-29 11:39:47","2020-02-21 04:58:48",7,"Frugal","semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a,",246,"USD","Open",9,"English"),
("Trip to United Arab Emirates!",25,"United Arab Emirates","2019-09-09 18:44:47","2020-10-24 00:50:25",12,"Frugal","eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue",132,"USD","Closed",10,"Spanish");

CREATE TABLE relations(
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  profile_id INTEGER(11) NOT NULL,
  trip_id INTEGER(11) NOT NULL, 
  relationship_type VARCHAR(30) NOT NULL,
  status VARCHAR(30) DEFAULT "Active",
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- Creating creator relations

INSERT INTO relations (profile_id, trip_id, relationship_type)
VALUES  (1,1,'creator'),
(1,2,'creator'),
(2,3,'creator'),
(17,4,'creator'),
(9,5,'creator'),
(30,6,'creator'),
(2,7,'creator'),
(3,8,'creator'),
(27,9,'creator'),
(22,10,'creator'),
(9,11,'creator'),
(7,12,'creator'),
(6,13,'creator'),
(21,14,'creator'),
(11,15,'creator'),
(12,16,'creator'),
(29,17,'creator'),
(29,18,'creator'),
(19,19,'creator'),
(25,20,'creator'),
(1,21,'creator'),
(8,22,'creator'),
(26,23,'creator'),
(25,24,'creator'),
(17,25,'creator'),
(24,26,'creator'),
(14,27,'creator'),
(13,28,'creator'),
(19,29,'creator'),
(7,30,'creator'),
(3,31,'creator'),
(16,32,'creator'),
(10,33,'creator'),
(9,34,'creator'),
(30,35,'creator'),
(15,36,'creator'),
(7,37,'creator'),
(19,38,'creator'),
(19,39,'creator'),
(11,40,'creator'),
(20,41,'creator'),
(11,42,'creator'),
(13,43,'creator'),
(3,44,'creator'),
(11,45,'creator'),
(6,46,'creator'),
(6,47,'creator'),
(3,48,'creator'),
(1,49,'creator'),
(30,50,'creator'),
(12,51,'creator'),
(26,52,'creator'),
(26,53,'creator'),
(22,54,'creator'),
(25,55,'creator'),
(10,56,'creator'),
(27,57,'creator'),
(15,58,'creator'),
(7,59,'creator'),
(13,60,'creator'),
(25,61,'creator'),
(22,62,'creator'),
(1,63,'creator'),
(20,64,'creator'),
(2,65,'creator'),
(25,66,'creator'),
(8,67,'creator'),
(7,68,'creator'),
(7,69,'creator'),
(29,70,'creator'),
(1,71,'creator'),
(18,72,'creator'),
(18,73,'creator'),
(18,74,'creator'),
(22,75,'creator'),
(11,76,'creator'),
(9,77,'creator'),
(10,78,'creator'),
(23,79,'creator'),
(29,80,'creator'),
(29,81,'creator'),
(7,82,'creator'),
(23,83,'creator'),
(23,84,'creator'),
(21,85,'creator'),
(3,86,'creator'),
(9,87,'creator'),
(19,88,'creator'),
(5,89,'creator'),
(6,90,'creator'),
(5,91,'creator'),
(4,92,'creator'),
(15,93,'creator'),
(29,94,'creator'),
(4,95,'creator'),
(1,96,'creator'),
(12,97,'creator'),
(15,98,'creator'),
(24,99,'creator'),
(18,100,'creator'),
(14,101,'creator'),
(2,102,'creator'),
(25,103,'creator');

INSERT INTO relations (profile_id, trip_id, relationship_type)
VALUES  (100, 1,"interested"),
(99, 2, "interested"),
(99, 3, "interested"),
(100, 4, "committed"),
(100, 5, "committed"),
(90, 1, "cancelled"),
(87, 1, "cancelled"),
(1, 20, "interested"),
(1, 25, "cancelled"),
(1, 18, "committed");